import { ArrowUpRight, CheckCircle2, CircleHelp, CreditCard, ShieldCheck, WalletCards } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";

const actions = [{ label: "Explore your wallet", detail: "View your demo balance and activity", icon: WalletCards }, { label: "Complete your profile", detail: "Review your account details", icon: ShieldCheck }, { label: "Get support", detail: "Contact the CediApp team", icon: CircleHelp }];

export default function ProtectedPage() {
  return <div className="space-y-8"><section className="rounded-3xl bg-primary p-7 text-primary-foreground md:p-10"><p className="text-sm font-medium text-primary-foreground/75">CediApp dashboard</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Welcome back. You are in control.</h1><p className="mt-3 max-w-xl text-primary-foreground/80">This is a demo dashboard for exploring the CediApp experience. Balances and activity below are illustrative, not real financial records.</p><Button asChild className="mt-6 bg-primary-foreground text-primary hover:bg-primary-foreground/90"><Link href="#actions">Continue setup <ArrowUpRight /></Link></Button></section>
  <section className="grid gap-4 md:grid-cols-3"><article className="rounded-2xl border bg-card p-6 shadow-sm md:col-span-2"><div className="flex items-start justify-between"><div><p className="text-sm text-muted-foreground">Demo wallet balance</p><p className="mt-2 text-3xl font-semibold">GH₵ 2,450.00</p></div><CreditCard className="size-6 text-primary" /></div><p className="mt-5 text-sm text-muted-foreground">Illustrative only — CediApp does not hold or move funds in this demo.</p></article><article className="rounded-2xl border bg-card p-6 shadow-sm"><p className="text-sm text-muted-foreground">Profile status</p><div className="mt-4 flex items-center gap-2 font-medium"><CheckCircle2 className="size-5 text-primary" /> Ready to explore</div><p className="mt-3 text-sm text-muted-foreground">Add your preferences when you are ready.</p></article></section>
  <section id="actions"><div className="flex items-end justify-between"><div><p className="text-sm font-medium text-primary">Next actions</p><h2 className="mt-1 text-2xl font-semibold">Keep your journey moving</h2></div></div><div className="mt-4 grid gap-4 md:grid-cols-3">{actions.map(({ label, detail, icon: Icon }) => <article key={label} className="rounded-2xl border bg-card p-6 shadow-sm"><Icon className="size-5 text-primary" /><h3 className="mt-5 font-semibold">{label}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{detail}</p><Button asChild className="mt-5 px-0" variant="link"><a href={label === "Get support" ? "mailto:support@cediapp.space" : "#"}>Open <ArrowUpRight /></a></Button></article>)}</div></section>
  <section className="rounded-2xl border border-amber-300/40 bg-amber-50 p-5 text-sm text-amber-950"><strong>Demo data notice.</strong> Figures, statuses, and journeys on this dashboard are for product demonstration only. Do not use them to make financial, legal, or identity decisions.</section></div>;
}
